# Generated by Django 5.2.3 on 2025-06-12 23:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ksiegowosc', '0002_account_delete_wydatki'),
    ]

    operations = [
        migrations.AlterField(
            model_name='account',
            name='account_type',
            field=models.CharField(choices=[('internal', 'Internal'), ('external', 'External')], max_length=250),
        ),
    ]
